[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "https://nexus-pre-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
